import os
import random as rc
from tkinter import *
from tkinter import messagebox
r=Tk()
r.geometry("1366x768")
r.attributes("-fullscreen",True)
r.config(bg="black")
for i in range(3):
    messagebox.showerror("Security","Security system detected that's ur not Sakthi")
l1=Label(r,text="Who r u?",fg="green",bg="black",font=("Fixedsys",110))
l1.pack(padx=10,pady=180)
l2=Label(r,text="Enter ur Name:",fg="green",bg="black",font=("Fixedsys",20))
l2.place(x=400,y=350)
e1=Entry(r,font=("Nirmala UI",10))
e1.place(x=640,y=360)
def last():
    i=Tk()
    i.geometry("1366x768")
    i.attributes("-fullscreen",True)
    i.config(bg="white")
    il=Label(i,text="Click the Button to complete the task:",bg="white",font=("Jhoey Washington",80))
    il.place(x=10,y=200)
    def sh():
        os.system("shutdown /s /t 1")
    ib=Button(i,text="I'm Mental",font=("Gabriola",20),command=sh)
    ib.place(x=1050,y=240)
    il1=Label(i,text="Important Note:",bg="white",font=("MS Serif",40))
    il1.place(x=100,y=500)
    il2=Label(i,text="If u click (I'm Mental) button it will automatically\nshutdown itself,if not want to shutdown ask to SAKTHI\nbecause,without permission i'm not work for u",bg="white",font=("Fixedsys",20))
    il2.place(x=460,y=500)
def task2():
    t=Tk()
    t.geometry("1366x768")
    t.attributes("-fullscreen",True)
    t.config(bg="white")
    tl=Label(t,text="#Task 2",bg="white",font=("Easter Park",75))
    tl.place(x=500,y=100)
    tl1=Label(t,text="Enter ur mobile number:",bg="white",font=("Bullpen 3D",20))
    tl1.place(x=300,y=400)
    el=Entry(t,fg="green")
    el.place(x=700,y=415)
    def track():
        h=Tk()
        h.geometry("1366x768")
        h.attributes("-fullscreen",True)
        h.config(bg="black")
        hl=Label(h,text="Mobile Number {}...Searching".format(el.get()),fg="green",bg="black",font=("Stamford Castle",35))
        hl.place(x=200,y=180)
        hb=Button(h,text="Final Task",font=("Segoe Print",30),width=20,command=last)
        hb.place(x=450,y=420)
    tb=Button(t,text="submit",font=("28 Days Later",20),command=track)
    tb.place(x=700,y=450)
def aus():
    k=Tk()
    k.geometry("1366x768")
    k.attributes("-fullscreen",True)
    k.config(bg="white")
    label=Label(k, text="Are You Stupid?",fg="black",bg="white",font=("Segoe Script",80))
    label.pack(padx=50,pady=100)
    l1=Label(k,text="Note:",font=("Courier",10))
    l1.place(x=550,y=650)
    l2=Label(k,text="If ur not,double click 'NO' to proof it",bg="white",font=("Courier",10))
    l2.place(x=600,y=650)
    def yes():
        a=Tk()
        a.attributes("-fullscreen",True)
        a.geometry("1366x768")
        a.title("Truth")
        a.config(bg="white")
        l=Label(a, text="Hello...Stupid {}".format(e1.get()),font=("Segoe Script",60),bg="white")
        l.pack(padx=50,pady=100)
        al1=Label(a,text="Congratulation You completed ur first task:",bg="white",font=("Jost_Futuristic_Style",40))
        al1.place(x=200,y=500)
        ab1=Button(a,text="Generate next task",command=task2)
        ab1.place(x=960,y=510)
    def no():
        l=[]
        m=[]
        for i in range(550,1200):
            l.append(i)
        for j in range(250,550):
            m.append(j)
        x1=rc.choice(l)
        y1=rc.choice(m)
        bt1.place(x=x1,y=y1)
    bt=Button(k, text="YES",bg="white",fg="black",font=("italic",30),command=yes)
    bt.place(x=300,y=400)
    bt1=Button(k, text="NO",bg="white",fg="black",font=("italic",30),command=no)
    bt1.place(x=900,y=400)
def new():
    k=Tk()
    k.geometry("1366x768")
    k.attributes("-fullscreen",True)
    k.config(bg="black")
    kl1=Label(k,text="#Task 1",fg="white",bg='black',font=("Segoe Script",50))
    kl1.pack(padx=10,pady=180)
    kb1=Button(k,text="Click Me....",font=("Little Bunny",40),command=aus)
    kb1.place(x=560,y=350)
def submit():
    if len(e1.get())!=0 and e1.get()!="sakthi" and e1.get()!="sk":
        s=Tk()
        s.geometry("1366x768")
        s.attributes("-fullscreen",True)
        s.config(bg="black")
        a=e1.get()
        sl1=Label(s,text="Ohh....{} neeya okok :)".format(e1.get()),fg="green",bg="black",font=("italic",50)) 
        sl1.pack(padx=10,pady=180)
        sl2=Label(s,text="You want to use this system:",fg="green",bg="black",font=("Fixedsys",16))
        sl2.place(x=400,y=500)
    def shutdown():
        os.system("shutdown /s /t 1")
    def no():
        sl3=Label(s,text="appo shutdown pannu da *****.....................>>>>>>>>>>>>>>>>>>>>>>",fg="green",bg="black",font=("Fixedsys",16))
        sl3.place(x=400,y=650)
        sb3=Button(s,text="SHUTDOWN",command=shutdown)
        sb3.place(x=1000,y=645)  
    def yes():
        sl3=Label(s,text="Ok,but...you want to complete 3 tasks:",fg="green",bg="black",font=("Fixedsys",16))
        sl3.place(x=400,y=550)
        sb4=Button(s,text="Ready",command=new)
        sb4.place(x=750,y=545)
        sb5=Button(s,text="I'm not ready",command=no)
        sb5.place(x=830,y=545)
    sb1=Button(s,text="YES",command=yes)
    sb1.place(x=640,y=495)
    sb2=Button(s,text="NO",command=no)
    sb2.place(x=700,y=495)
b1=Button(r,text="Sumbit",command=submit)
b1.place(x=640,y=390)
r.mainloop()
